### ISSUE TITLE
Bugs in calling event

### ISSUE THREAD

**Issue by Yosshi999** [MinecrafterJPN/PocketMoney#6]
Arg2 of MoneyUpdateEvent and Arg2&3 of TransactionEvent must be instanceof Player,
 so when you run "/money pay(wd) NonPlayer (amount)", some error will happen on L119-135 or L190 because getPlayer() returns null.

**Comment by Yosshi999** [comment]
In fact, when you withdraw from NonPlayer, the nonplayer lose money but you can't get the money.

**Comment by MinecrafterJPN** [comment]
Thanks.
I'll fix it.
